### PR TITLE
fix bug: send more invalid bytes to server caused exception

### PR DESCRIPTION
**Pull request by jiaminzou888**
fix bug: send more invalid bytes to server caused exception when encoding request data

### CODE REVIEW

**Review by jnlunsb — COMMENTED** [review]
private static ByteBuffer jsonObjectToTarsStream(JsonObject rootObj) {
        JsonOutputStream oos = new JsonOutputStream();
        oos.write(rootObj);
        return oos.getByteBuffer();
    }


private static boolean isTarsStruct(JsonObject jsonObject) {
        try {
            jsonObjectToTarsStream(jsonObject);
            return true;
        } catch (JsonEncodeException e) {
            return false;
        }
    }

Only for isTarsStruct，distinguish the inputing parameter

**Review by jnlunsb — COMMENTED** [review]
You are right.

**Comment by jnlunsb** [comment]
@FlyCatZout It doesn't affect stream interaction but it will take invalid bytes to Server. So it should be merged.

**Comment by boycs007** [comment]
If the user calculates the amount of data sent and received by JMeter, he will get an incorrect result. we have to fix this bug.

**Comment by jiaminzou888** [comment]
```java   
 private static ByteBuffer jsonObjectToTarsStream(JsonObject rootObj) {
        JsonOutputStream oos = new JsonOutputStream();
        oos.write(rootObj);
        return oos.getByteBuffer();
}
```
// -------------------
```java
public static ByteBuffer paramsToJceStream(Object[] objs) {
        if (objs.length > 0 && objs[0] instanceof JsonObject) {
            JsonObject rootObj = generateFullJsonObject(objs);
            return jsonObjectToTarsStream(rootObj);
        } else {
           ....
        }
    }
```

// -------------------
```java
  ByteBuffer bf = TupUtil.paramsToJceStream(context.getArgumentValues());
  localErrorCode += this.sendRequestPacket(bf.array());
```

// -------------------

```java
public boolean skipToTag(int tag) {
        try {
            ......
        } catch (TarsDecodeException e) {
        } catch (BufferUnderflowException e) {
        }
        return false;
}

```

here will has an un-catched **IllegalArgumentException** when invalid bytes send to the server
@jnlunsb @boycs007

**Pull request merged**
